---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  chart:
    repository: https://helm.releases.hashicorp.com
    name: vault
    version: 0.20.1
